from lib4package.metadata import Metadata

print ("PYTHON TESTS")
print ("============")
m = Metadata("python", debug=False)
for p in ["lib4sbom", "idna"]:
    print (f"Process package {p}")
    m.get_package(p)
    # print (m.print_data())
    print ("Show Checksum")
    m.show_checksum()
    print ("Package Description")
    print(m.get_description())
    print ("Package homepage")
    print(m.get_homepage())
    print ("Package Licncse")
    print(m.get_license())
    print ("Latest release")
    print(m.get_latest_release())
    print ("Checksum for latest release (default)")
    print(m.get_checksum())
    print ("Checksum for latest release (explicit)")
    print(m.get_checksum(version = m.get_latest_release()))
    print ("Package Originator")
    print(m.get_originator())
print ("\nJAVA TESTS")
print ("==========")
m = Metadata("java")
p = "org.slf4j:slf4j-api"
print(f"Process package {p}")
m.get_package(p)
# print (m.print_data())
print("Show Checksum")
m.show_checksum()
print("Package Description")
print(m.get_description())
print("Package homepage")
print(m.get_homepage())
print("Package Licncse")
print(m.get_license())
print("Latest release")
print(m.get_latest_release())
print("Checksum for latest release (default)")
print(m.get_checksum())
print("Checksum for latest release (explicit)")
print(m.get_checksum(version=m.get_latest_release()))
print("Package Originator")
print(m.get_originator())
